apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: demo-ec2-instance
spec:
  forProvider:
    region: us-east-1
    imageId: ami-0dc2d3e4c0f9ebd18
    blockDeviceMappings:
     - deviceName: /dev/sdx
       ebs:
         volumeSize: 30
    securityGroupRefs:
      - name: sample-sg 
    subnetIdRef:
      name: sample-subnet
  providerConfigRef:
    name: default
